export const FETCH_SHOPS_INIT = 'FETCH_SHOPS_INIT';
export const FETCH_SHOPS_SUCCESS= 'FETCH_SHOPS_SUCCESS';
export const FETCH_SHOPS_FAILURE = 'FETCH_SHOPS_FAILURE';

export const FETCH_SHOP_INIT = 'FETCH_SHOP_INIT';
export const FETCH_SHOP_SUCCESS= 'FETCH_SHOP_SUCCESS';
export const FETCH_SHOP_FAILURE = 'FETCH_SHOP_FAILURE';

export const EDIT_COVERPAGE_INIT =  'EDIT_COVERPAGE_INIT';
export const EDIT_COVERPAGE_SUCCESS=  'EDIT_COVERPAGE_SUCCESS';
export const EDIT_COVERPAGE_FAILURE =  'EDIT_COVERPAGE_FAILURE';

export const EDIT_INFO_INIT =  'EDIT_INFO_INIT';
export const EDIT_INFO_SUCCESS=  'EDIT_INFO_SUCCESS';
export const EDIT_INFO_FAILURE =  'EDIT_INFO_FAILURE';

export const EDIT_DESC_INIT =  'EDIT_DESC_INIT';
export const EDIT_DESC_SUCCESS=  'EDIT_DESC_SUCCESS';
export const EDIT_DESC_FAILURE =  'EDIT_DESC_FAILURE';

export const FETCH_MY_SHOP_INIT = 'FETCH_MY_SHOP_INIT';
export const FETCH_MY_SHOP_SUCCESS= 'FETCH_MY_SHOP_SUCCESS';
export const FETCH_MY_SHOP_FAILURE = 'FETCH_MY_SHOP_FAILURE';

export const FETCH_MY_SHOPS_INIT = 'FETCH_MY_SHOPS_INIT';
export const FETCH_MY_SHOPS_SUCCESS= 'FETCH_MY_SHOPS_SUCCESS';
export const FETCH_MY_SHOPS_FAILURE = 'FETCH_MY_SHOPS_FAILURE';

export const ADD_SHOP_INIT = 'ADD_SHOP_INIT';
export const ADD_SHOP_SUCCESS = 'ADD_SHOP_SUCCESS';
export const ADD_SHOP_FAILURE = 'ADD_SHOP_FAILURE';

export const ADD_IMG_INIT = 'ADD_IMG_INIT';
export const ADD_IMG_SUCCESS = 'ADD_IMG_SUCCESS';
export const ADD_IMG_FAILURE = 'ADD_IMG_FAILURE';

export const ADD_OFFER_IMG_INIT = 'ADD_OFFER_IMG_INIT';
export const ADD_OFFER_IMG_SUCCESS = 'ADD_OFFER_IMG_SUCCESS';
export const ADD_OFFER_IMG_FAILURE = 'ADD_OFFER_IMG_FAILURE';

export const DEL_IMG_INIT = 'DEL_IMG_INIT';
export const DEL_IMG_SUCCESS = 'DEL_IMG_SUCCESS';
export const DEL_IMG_FAILURE = 'DEL_IMG_FAILURE';

//User
export const LOG_IN_INIT = 'LOG_IN_INTI';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT_SUCCES = 'LOG_OUT_SUCCES';

export const FETCH_MY_USER_INIT = 'FETCH_MY_USER_INIT';
export const FETCH_MY_USER_SUCCESS= 'FETCH_MY_USER_SUCCESS';
export const FETCH_MY_USER_FAILURE = 'FETCH_MY_USER_FAILURE';

export const ADD_USER_INIT = 'ADD_USER_INIT'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const FETCH_USER_INIT = 'FETCH_USER_INIT';
export const FETCH_USER_SUCCESS= 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_OFFERS_INIT = 'FETCH_OFFERS_INIT';
export const FETCH_OFFERS_SUCCESS = 'FETCH_OFFERS_SUCCESS';
export const FETCH_OFFERS_FAILURE = 'FETCH_OFFERS_FAILURE';

export const ADD_OFFER_INIT = 'ADD_OFFER_INIT';
export const ADD_OFFER_SUCCESS = 'ADD_OFFER_SUCCESS';
export const ADD_OFFER_FAILURE = 'ADD_OFFER_FAILURE';

export const ADD_REVIEW_INIT = 'ADD_REVIEW_INIT';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE';
